-- 1. RECRUITERS TABLE
CREATE TABLE IF NOT EXISTS recruiters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    company_name TEXT,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. JOBS TABLE
CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recruiter_id BIGINT REFERENCES recruiters(id) ON DELETE SET NULL, -- Link to recruiter
    job_index BIGINT UNIQUE NOT NULL, -- MUST match FAISS index
    job_title TEXT NOT NULL,
    company TEXT NOT NULL,
    location TEXT,
    description TEXT,
    job_link TEXT DEFAULT '#',
    skills TEXT[], -- Array of strings for skills
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CANDIDATES TABLE
CREATE TABLE IF NOT EXISTS candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, -- Link to Supabase Auth
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    resume_text TEXT,
    edu_score FLOAT DEFAULT 0,
    years_exp FLOAT DEFAULT 0,
    skill_score FLOAT DEFAULT 0,
    profile_quality FLOAT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. APPLICATIONS / MATCHES TABLE (Optional but recommended)
CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT REFERENCES candidates(id) ON DELETE CASCADE,
    job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
    match_score FLOAT,
    status TEXT DEFAULT 'applied', -- 'applied', 'shortlisted', 'rejected'
    applied_at TIMESTAMPTZ DEFAULT NOW()
);

-- INDEXES for faster lookups
CREATE INDEX IF NOT EXISTS idx_jobs_job_index ON jobs(job_index);
CREATE INDEX IF NOT EXISTS idx_candidates_email ON candidates(email);

-- ==========================================
-- ROW LEVEL SECURITY (RLS)
-- ==========================================

-- 1. Enable RLS on all tables
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE recruiters ENABLE ROW LEVEL SECURITY;

-- 2. RECRUITERS Policies
CREATE POLICY "Recruiters can view own profile" ON recruiters FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Recruiters can create own profile" ON recruiters FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Recruiters can update own profile" ON recruiters FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Service role full access to recruiters" ON recruiters TO service_role USING (true) WITH CHECK (true);

-- 3. JOBS Policies: Anyone can view, recruiters can manage their own
CREATE POLICY "Allow public read access to jobs" ON jobs FOR SELECT USING (true);
CREATE POLICY "Recruiters can manage their own jobs" ON jobs FOR ALL USING (
    recruiter_id IN (SELECT id FROM recruiters WHERE user_id = auth.uid())
);
CREATE POLICY "Allow service role full access to jobs" ON jobs TO service_role USING (true) WITH CHECK (true);

-- 4. CANDIDATES Policies: Users manage their own data
CREATE POLICY "Candidates can view own profile" ON candidates FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Candidates can create own profile" ON candidates FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Candidates can update own profile" ON candidates FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Service role full access to candidates" ON candidates TO service_role USING (true) WITH CHECK (true);

-- 5. APPLICATIONS Policies: Users manage their own applications
CREATE POLICY "Candidates can view own applications" ON applications FOR SELECT USING (
    candidate_id IN (SELECT id FROM candidates WHERE user_id = auth.uid())
);
CREATE POLICY "Candidates can create own applications" ON applications FOR INSERT WITH CHECK (
    candidate_id IN (SELECT id FROM candidates WHERE user_id = auth.uid())
);
CREATE POLICY "Recruiters can view applications for their jobs" ON applications FOR SELECT USING (
    job_id IN (SELECT id FROM jobs WHERE recruiter_id IN (SELECT id FROM recruiters WHERE user_id = auth.uid()))
);
CREATE POLICY "Service role full access to applications" ON applications TO service_role USING (true) WITH CHECK (true);
