/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterIndexRouteImport } from './routes/recruiter.index'
import { Route as CandidateIndexRouteImport } from './routes/candidate.index'
import { Route as RecruiterSettingsRouteImport } from './routes/recruiter.settings'
import { Route as RecruiterDashboardRouteImport } from './routes/recruiter.dashboard'
import { Route as CandidateRecommendedRouteImport } from './routes/candidate.recommended'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateDashboardRouteImport } from './routes/candidate.dashboard'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate.applications'
import { Route as RecruiterJobsJobIdRouteImport } from './routes/recruiter.jobs.$jobId'

const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterIndexRoute = RecruiterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecruiterRoute,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidateRoute,
} as any)
const RecruiterSettingsRoute = RecruiterSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterDashboardRoute = RecruiterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RecruiterRoute,
} as any)
const CandidateRecommendedRoute = CandidateRecommendedRouteImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => CandidateRoute,
} as any)
const RecruiterJobsJobIdRoute = RecruiterJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => RecruiterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/recruiter': typeof RecruiterRouteWithChildren
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/recommended': typeof CandidateRecommendedRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/candidate/': typeof CandidateIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/recruiter/jobs/$jobId': typeof RecruiterJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/recommended': typeof CandidateRecommendedRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/candidate': typeof CandidateIndexRoute
  '/recruiter': typeof RecruiterIndexRoute
  '/recruiter/jobs/$jobId': typeof RecruiterJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/recruiter': typeof RecruiterRouteWithChildren
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/recommended': typeof CandidateRecommendedRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/candidate/': typeof CandidateIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/recruiter/jobs/$jobId': typeof RecruiterJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/candidate'
    | '/recruiter'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/profile'
    | '/candidate/recommended'
    | '/recruiter/dashboard'
    | '/recruiter/settings'
    | '/candidate/'
    | '/recruiter/'
    | '/recruiter/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/profile'
    | '/candidate/recommended'
    | '/recruiter/dashboard'
    | '/recruiter/settings'
    | '/candidate'
    | '/recruiter'
    | '/recruiter/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/candidate'
    | '/recruiter'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/profile'
    | '/candidate/recommended'
    | '/recruiter/dashboard'
    | '/recruiter/settings'
    | '/candidate/'
    | '/recruiter/'
    | '/recruiter/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CandidateRoute: typeof CandidateRouteWithChildren
  RecruiterRoute: typeof RecruiterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/': {
      id: '/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof RecruiterIndexRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/recruiter/settings': {
      id: '/recruiter/settings'
      path: '/settings'
      fullPath: '/recruiter/settings'
      preLoaderRoute: typeof RecruiterSettingsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/dashboard': {
      id: '/recruiter/dashboard'
      path: '/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof RecruiterDashboardRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/candidate/recommended': {
      id: '/candidate/recommended'
      path: '/recommended'
      fullPath: '/candidate/recommended'
      preLoaderRoute: typeof CandidateRecommendedRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/recruiter/jobs/$jobId': {
      id: '/recruiter/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/recruiter/jobs/$jobId'
      preLoaderRoute: typeof RecruiterJobsJobIdRouteImport
      parentRoute: typeof RecruiterRoute
    }
  }
}

interface CandidateRouteChildren {
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateRecommendedRoute: typeof CandidateRecommendedRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
}

const CandidateRouteChildren: CandidateRouteChildren = {
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateRecommendedRoute: CandidateRecommendedRoute,
  CandidateIndexRoute: CandidateIndexRoute,
}

const CandidateRouteWithChildren = CandidateRoute._addFileChildren(
  CandidateRouteChildren,
)

interface RecruiterRouteChildren {
  RecruiterDashboardRoute: typeof RecruiterDashboardRoute
  RecruiterSettingsRoute: typeof RecruiterSettingsRoute
  RecruiterIndexRoute: typeof RecruiterIndexRoute
  RecruiterJobsJobIdRoute: typeof RecruiterJobsJobIdRoute
}

const RecruiterRouteChildren: RecruiterRouteChildren = {
  RecruiterDashboardRoute: RecruiterDashboardRoute,
  RecruiterSettingsRoute: RecruiterSettingsRoute,
  RecruiterIndexRoute: RecruiterIndexRoute,
  RecruiterJobsJobIdRoute: RecruiterJobsJobIdRoute,
}

const RecruiterRouteWithChildren = RecruiterRoute._addFileChildren(
  RecruiterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CandidateRoute: CandidateRouteWithChildren,
  RecruiterRoute: RecruiterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
